#!/usr/bin/env python3
"""Bake the Tank Gauge's assets into a PROGMEM header (roadmap 1.6.6).

    python3 make_assets.py

**The artwork is not duplicated.** This module and `GaugeWifi` are the same panel down
the same wire grammar over a different pipe, so they read the same `assets/` folder —
the one in `GaugeWifi`, which owns it. Copying the PNG and the SVG into a second sketch
folder would mean two copies to keep in step, and the first time they drifted the two
transports would stop being a fair comparison: any difference on screen could be the
pipe or could be the artwork, and nobody could tell which.

One source, two generated headers. The headers are generated and never hand-edited, so
what reaches the board over Bluetooth is byte-for-byte what reaches it over WiFi — which
is the whole point of running the panel down a second transport.

Everything else is as `GaugeWifi/make_assets.py`, including CRC32 at build time
(module-sdk.md §8) as lowercase unpadded hex.
"""
import zlib
from pathlib import Path

HERE = Path(__file__).parent

# The shared artwork. GaugeWifi owns the folder; this module reads it.
ASSETS = HERE.parent / "GaugeWifi" / "assets"

ORDER = ["h_large_day.json", "dial.png", "gauge.svg"]


def block_name(filename: str) -> str:
    return filename[:-5] if filename.endswith(".json") else filename


def c_array(data: bytes, indent: str = "  ") -> str:
    lines = []
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(indent + row + ",")
    return "\n".join(lines)


assets = []
for filename in ORDER:
    path = ASSETS / filename
    if not path.exists():
        raise SystemExit(f"missing asset: {path}")
    assets.append((block_name(filename), path.read_bytes()))

total = sum(len(d) for _, d in assets)

out = [
    "/* GENERATED by make_assets.py — do not edit.",
    " *",
    " * This module's install payload, baked into flash. Assets are streamed a chunk at a",
    " * time straight out of PROGMEM (module-sdk.md §8), never held whole in RAM — which is",
    " * what lets a board with kilobytes of memory ship a panel of any size.",
    " *",
    " * Generated from ../GaugeWifi/assets — the same artwork the WiFi module ships.",
    " */",
    "#ifndef GAUGE_ASSETS_H",
    "#define GAUGE_ASSETS_H",
    "",
    "#include <Arduino.h>",
    "",
    "struct DashAsset {",
    "  const char*    name;    // the BLOCK name — a slot name means it is a layout",
    "  const uint8_t* bytes;   // in PROGMEM: read with pgm_read_byte",
    "  uint32_t       length;  // exact byte count, sent in the BLOCK header",
    "  const char*    crc;     // CRC32, lowercase hex, unpadded (§8)",
    "};",
    "",
]

for i, (name, data) in enumerate(assets):
    crc = zlib.crc32(data) & 0xFFFFFFFF
    out.append(f"// {name} — {len(data)} bytes, crc32 {crc:x}")
    out.append(f"static const uint8_t ASSET_{i}[] PROGMEM = {{")
    out.append(c_array(data))
    out.append("};")
    out.append("")

out.append("static const DashAsset DASH_ASSETS[] = {")
for i, (name, data) in enumerate(assets):
    crc = zlib.crc32(data) & 0xFFFFFFFF
    out.append(f'  {{ "{name}", ASSET_{i}, {len(data)}UL, "{crc:x}" }},')
out.append("};")
out.append("")
out.append(f"static const uint8_t  DASH_ASSET_COUNT       = {len(assets)};")
out.append(f"static const uint32_t DASH_ASSET_TOTAL_BYTES = {total}UL;")
out.append("")
out.append("#endif  // GAUGE_ASSETS_H")

(HERE / "gauge_assets.h").write_text("\n".join(out) + "\n")

for name, data in assets:
    print(f"  {name:16} {len(data):>7} bytes  crc32 {zlib.crc32(data) & 0xFFFFFFFF:x}")
print(f"  {'TOTAL':16} {total:>7} bytes in {len(assets)} blocks")
