/* ===========================================================================
   DASH Module — Tank Gauge (WiFi)        |  module type: ACCESSORY
   Board: Espressif ESP32 DevKitC (WROOM-32, classic)  |  transport: WiFi TCP
   Built on the DashModule library.       |  roadmap 1.6.5
   ---------------------------------------------------------------------------
   THE FIRST ACCESSORY. Every module before this one was invisible — a SYSTEM
   module publishes signals, a LISTENER consumes them, and neither puts anything
   on screen. This one owns a panel: it ships the artwork DASH draws, and then
   feeds it live values.

   WHAT IT SENDS, AND WHEN
     On INSTALL it streams three blocks out of flash — the layout document, and
     the two pieces of artwork the layout refers to:

       h_large_day   the panel description for the large horizontal slot
       dial.png      the gauge face
       gauge.svg     the needle, ticks, readout and lamp

     Then it goes quiet until ACTIVATE, and reports a simulated tank pressure.

   THE LAYOUT IS THE DECLARATION (module-layout.md §9)
     An ACCESSORY declares no variables and no controls separately. The layout
     names every variable it binds and every control it can send, so DASH learns
     both by reading it. There is nothing else to declare — which is why this
     sketch's onInstall() is three blocks and nothing more.

   NO DashAccessory YET — AND THAT IS DELIBERATE
     The library ships DashSystem and DashListener; the ACCESSORY helper is held
     back to roadmap 1.6.10, so that it is written from something that has been
     proven on hardware rather than from the specification alone. That is the same
     order 1.4.15 used for the other two. The class below is therefore a hand-built
     stand-in, and it is the draft that helper gets extracted from — so it is
     written as if a stranger had to read it.

   ASSETS LIVE IN FLASH AND ARE STREAMED (module-sdk.md §8)
     gauge_assets.h is generated by make_assets.py from the files in assets/, with
     each CRC32 computed at build time. Nothing is ever held whole in RAM: blocks
     go out a chunk at a time straight from PROGMEM, which is what lets a board
     with kilobytes of memory ship a panel of any size.

   FIRST BUILD: copy arduino_secrets.h.example to arduino_secrets.h in this folder
   and fill it in — SECRET_SSID, SECRET_PASS, DASH_HOST (the DASH device's IP),
   DASH_PORT (3274). Your copy is gitignored; the .example is not.
   =========================================================================== */
#include <Dash.h>
#include <WiFi.h>              // ESP32 core radio
#include "arduino_secrets.h"   // SECRET_SSID / SECRET_PASS / DASH_HOST / DASH_PORT
#include "gauge_assets.h"      // GENERATED — run make_assets.py after changing assets/

WiFiClient client;
#define DBG Serial

/* ---------------------------------------------------------------------------
   The ACCESSORY face — the 1.6.10 helper in draft.

   Everything type-specific an ACCESSORY does lives here: announce the payload,
   stream it, and report values while active. The base class already handles the
   framing, HELLO, the INSTALL_END that closes the handshake, and the SILENT ->
   ACTIVE -> SILENT lifecycle with its ROGERs.
   --------------------------------------------------------------------------- */
class DashAccessoryDraft : public DashModule {
 public:
  DashAccessoryDraft(const char* id, const char* name, const char* description,
                     const char* version)
      : DashModule(id, "ACCESSORY", name, description, version) {}

  // REPORT|id|variable|value — this panel's own data, addressed to this module.
  // Sourceful: DASH keeps the id as the store key, because `tank_pressure` from
  // this module is this panel's data and is never merged with anybody else's.
  void report(const char* variable, float value, int decimals) {
    startMsg(F("REPORT"));
    field(variable);
    fieldFloat(value, decimals);
    endMsg();
  }

 protected:
  void onActivated() override {
    Serial.println(F("[dash] ACTIVE — reporting tank_pressure"));
  }

  void onDeactivated() override {
    Serial.println(F("[dash] SILENT"));
  }

  /* The install payload. MANIFEST first as a table of contents, so DASH can show
     a real progress bar rather than an indeterminate one, then the blocks. The
     base sends INSTALL_END after this returns. */
  void onInstall() override {
    startMsg(F("MANIFEST"));
    fieldInt(DASH_ASSET_COUNT);
    fieldInt((long)DASH_ASSET_TOTAL_BYTES);
    endMsg();

    for (uint8_t i = 0; i < DASH_ASSET_COUNT; i++) sendBlock(DASH_ASSETS[i]);
  }

 private:
  /* One asset: the header line, then exactly `length` raw bytes.

     THE BYTE COUNT IS THE FRAMING. Once the header is out, the next `length`
     bytes are payload and nothing else — a 0x0A inside a PNG is data, not a line
     ending. DASH switches to a counted read on seeing the header and switches
     back when the count is met, which is what lets binary travel down a wire that
     is otherwise line-based.

     A MODULE NEVER PARSES ITS OWN LAYOUT. This copies bytes from flash to a
     socket and understands none of them; making sense of the payload is entirely
     DASH's job. That is why an eight-bit board with an SD card could ship a panel
     it could not begin to render itself. */
  void sendBlock(const DashAsset& asset) {
    startMsg(F("BLOCK"));
    fieldRaw(asset.name);        // generated constants — no stripping needed
    fieldInt((long)asset.length);
    fieldRaw(asset.crc);
    endMsg();

    uint8_t chunk[CHUNK];
    uint32_t sent = 0;
    while (sent < asset.length) {
      uint16_t n = (asset.length - sent > CHUNK) ? CHUNK : (uint16_t)(asset.length - sent);
      for (uint16_t i = 0; i < n; i++) chunk[i] = pgm_read_byte(asset.bytes + sent + i);

      // Write the chunk out completely before moving on. A Stream may accept fewer
      // bytes than offered when its buffer is full, and a block that is even one
      // byte short is a length mismatch at the far end — after the whole payload
      // has been sent. So push the remainder rather than assuming it went.
      //
      // Deliberately NOT flush(): on the ESP32 core that drains the *receive*
      // buffer, which would quietly eat inbound DASH messages mid-install.
      uint16_t written = 0;
      while (written < n) {
        size_t w = _io->write(chunk + written, n - written);
        if (w == 0) { yield(); continue; }   // socket busy — let the stack breathe
        written += w;
      }
      sent += n;
      yield();
    }
  }

  static const uint16_t CHUNK = 512;   // one working buffer, reused for every asset
};

/* -------- the module ---------------------------------------------------------- */
// A distinct id from the SYSTEM modules on the bench so all of them can coexist.
// **The version is bumped whenever the layout changes, and that is not bookkeeping.** DASH
// captured this string at install and compares it against every HELLO (roadmap 1.4.13), so a
// module whose artwork or bindings have moved on while its version stands still would keep
// being drawn from the layout already on the tablet's disk. Bumping it is what makes DASH
// quarantine the stale record and offer the update that re-runs the handshake.
DashAccessoryDraft dash("0000DA58AC01", "Tank Gauge",
                        "Air-ride tank pressure panel over WiFi", "v1.2");

/* -------- this board's own pretend tank --------------------------------------- */
// No sensor wired up (roadmap 1.6.5 is about the path, not the plumbing), so the
// value is generated. A slow sweep across the full range makes the whole scale
// visible without anyone having to turn anything.
float pressure = 0.0;
bool  rising   = true;
const float PRESSURE_MIN = 0.0, PRESSURE_MAX = 11.0, PRESSURE_STEP = 0.1;

unsigned long lastReport  = 0;
unsigned long lastLinkTry = 0;
const unsigned long REPORT_MS = 250, LINK_RETRY_MS = 3000;

bool linkUp = false;

/* -------- WiFi: associate, connect, and go SILENT on any drop ------------------ */
// The inversion described in BodyWifi applies here too: on USB, DASH opens the
// device; on WiFi, DASH runs the server and this module is the client that dials
// in. So the firmware's extra job is keeping that socket up — and, the important
// part, calling linkLost() the moment it is not, because a dead socket sends no
// DEACTIVATE and the module would otherwise believe it was still active.
void maintainLink() {
  if (client.connected()) { linkUp = true; return; }

  if (linkUp) {
    DBG.println(F("[wifi] link lost — going SILENT"));
    dash.linkLost();
    linkUp = false;
  }

  unsigned long now = millis();
  if (now - lastLinkTry < LINK_RETRY_MS) return;
  lastLinkTry = now;

  if (WiFi.status() != WL_CONNECTED) {
    DBG.print(F("[wifi] associating to ")); DBG.println(SECRET_SSID);
    WiFi.begin(SECRET_SSID, SECRET_PASS);
    return;                       // try the socket on a later pass
  }

  DBG.print(F("[wifi] connecting to DASH at "));
  DBG.print(DASH_HOST); DBG.print(':'); DBG.println(DASH_PORT);
  if (client.connect(DASH_HOST, DASH_PORT)) {
    DBG.println(F("[wifi] connected"));
    linkUp = true;
  }
}

void setup() {
  DBG.begin(115200);
  delay(200);
  DBG.println();
  DBG.println(F("DASH Tank Gauge (ACCESSORY over WiFi)"));
  DBG.print(F("payload: ")); DBG.print(DASH_ASSET_COUNT);
  DBG.print(F(" blocks, ")); DBG.print(DASH_ASSET_TOTAL_BYTES); DBG.println(F(" bytes"));

  WiFi.mode(WIFI_STA);
  dash.begin(client);            // a WiFiClient is a Stream; the library drives it
}

void loop() {
  maintainLink();
  dash.loop();

  if (!dash.isActive()) return;  // SILENT until DASH says otherwise (§6)

  unsigned long now = millis();
  if (now - lastReport >= REPORT_MS) {
    lastReport = now;
    pressure += rising ? PRESSURE_STEP : -PRESSURE_STEP;
    if (pressure >= PRESSURE_MAX) { pressure = PRESSURE_MAX; rising = false; }
    if (pressure <= PRESSURE_MIN) { pressure = PRESSURE_MIN; rising = true;  }
    dash.report("tank_pressure", pressure, 1);
  }
}
