/* ===========================================================================
   DASH Module — Tank Gauge (WiFi)        |  module type: ACCESSORY
   Board: Espressif ESP32 DevKitC (WROOM-32, classic)  |  transport: WiFi TCP
   Built on the DashModule library.       |  roadmap 1.6.5
   ---------------------------------------------------------------------------
   THE FIRST ACCESSORY. Every module before this one was invisible — a SYSTEM
   module publishes signals, a LISTENER consumes them, and neither puts anything
   on screen. This one owns a panel: it ships the artwork DASH draws, and then
   feeds it live values.

   WHAT IT SENDS, AND WHEN
     On INSTALL it streams three blocks out of flash — the layout document, and
     the two pieces of artwork the layout refers to:

       h_large_day   the panel description for the large horizontal slot
       dial.png      the gauge face
       gauge.svg     the needle, ticks, lamp and the three buttons

     Then it goes quiet until ACTIVATE, dumps everything it has, and from then
     on reports tank_pressure whenever it changes.

   THE TANK IS DRIVEN BY THE PANEL, NOT BY A TIMER (roadmap 1.6.7)
     Up to 1.6.6 this module ran a slow sweep across the whole range, which
     proved the needle moved but could never prove *why* it moved. Now nothing
     moves unless somebody presses something, so every movement on screen is
     attributable to the press that caused it — which is the entire point of the
     version, and worth losing the free demo for.

   WHAT THE THREE BUTTONS EXERCISE (module-layout.md §8)
     PLUS and MINUS are momentary — "one more than it is now" is not a value
     anybody can name in advance, so they carry none, DASH predicts nothing, and
     the needle moves when this module says it moved.

     ZERO names the variable and carries a literal, so DASH draws it immediately
     and waits to be told it was right. All three outcomes are reachable from
     this one panel: press ZERO and it is confirmed; press PLUS at 11 bar and
     the clamp below reports 11 unchanged, which is "heard, and could not
     comply" and is not an error; pull the power and press ZERO and the panel
     reverts when nothing answers.

   THE MODULE REPORTS FACTS. IT NEVER ISSUES INSTRUCTIONS (§8)
     Nothing below mentions a needle, a colour, a button or a panel. This module
     says what its pressure is; the layout decides what that looks like. That is
     why the same firmware would drive a completely redrawn panel without a line
     of it changing.

   THE LAYOUT IS THE DECLARATION (module-layout.md §9)
     An ACCESSORY declares no variables and no controls separately. The layout
     names every variable it binds and every control it can send, so DASH learns
     both by reading it. There is nothing else to declare — which is why this
     sketch's onInstall() is three blocks and nothing more.

   NO DashAccessory YET — AND THAT IS DELIBERATE
     The library ships DashSystem and DashListener; the ACCESSORY helper is held
     back to roadmap 1.6.10, so that it is written from something that has been
     proven on hardware rather than from the specification alone. That is the same
     order 1.4.15 used for the other two. The class below is therefore a hand-built
     stand-in, and it is the draft that helper gets extracted from — so it is
     written as if a stranger had to read it.

   ASSETS LIVE IN FLASH AND ARE STREAMED (module-sdk.md §8)
     gauge_assets.h is generated by make_assets.py from the files in assets/, with
     each CRC32 computed at build time. Nothing is ever held whole in RAM: blocks
     go out a chunk at a time straight from PROGMEM, which is what lets a board
     with kilobytes of memory ship a panel of any size.

   FIRST BUILD: copy arduino_secrets.h.example to arduino_secrets.h in this folder
   and fill it in — SECRET_SSID, SECRET_PASS, DASH_HOST (the DASH device's IP),
   DASH_PORT (3274). Your copy is gitignored; the .example is not.
   =========================================================================== */
#include <Dash.h>
#include <WiFi.h>              // ESP32 core radio
#include "arduino_secrets.h"   // SECRET_SSID / SECRET_PASS / DASH_HOST / DASH_PORT
#include "gauge_assets.h"      // GENERATED — run make_assets.py after changing assets/

WiFiClient client;
#define DBG Serial

/* ---------------------------------------------------------------------------
   The ACCESSORY face — the 1.6.10 helper in draft.

   Everything type-specific an ACCESSORY does lives here: announce the payload,
   stream it, and report values while active. The base class already handles the
   framing, HELLO, the INSTALL_END that closes the handshake, and the SILENT ->
   ACTIVE -> SILENT lifecycle with its ROGERs.
   --------------------------------------------------------------------------- */
class DashAccessoryDraft : public DashModule {
 public:
  DashAccessoryDraft(const char* id, const char* name, const char* description,
                     const char* version)
      : DashModule(id, "ACCESSORY", name, description, version) {}

  // REPORT|id|variable|value — this panel's own data, addressed to this module.
  // Sourceful: DASH keeps the id as the store key, because `tank_pressure` from
  // this module is this panel's data and is never merged with anybody else's.
  void report(const char* variable, float value, int decimals) {
    startMsg(F("REPORT"));
    field(variable);
    fieldFloat(value, decimals);
    endMsg();
  }

  // A control on the panel was pressed. The builder gets the control name and
  // the value the layout attached to it — an empty string for a momentary one.
  void onAction(void (*cb)(const char* control, const char* value)) { _onAction = cb; }

  // Just went ACTIVE. **Send everything you have here** (§8): the panel is drawn
  // from DASH's store, and until something arrives there is nothing in it, so a
  // module that waits for its next change leaves the panel blank until then.
  void onActivate(void (*cb)()) { _onActivate = cb; }

 protected:
  void onActivated() override {
    Serial.println(F("[dash] ACTIVE — dumping state"));
    if (_onActivate) _onActivate();
  }

  /* ACTION|id|control|value — the inbound half of the specific column, and the
     only message an ACCESSORY receives that is about its own panel.

     The base class has already checked the id, so anything arriving here was
     addressed to this module. A control this module does not recognise is
     ignored in silence: the layout on the tablet may be newer than the firmware
     on the board, and refusing a press with an error would turn an ordinary
     version skew into a fault. */
  void onCommand(int argc, char** argv) override {
    if (strcmp(argv[0], "ACTION") != 0) return;
    if (argc < 3) return;
    if (_onAction) _onAction(argv[2], argc > 3 ? argv[3] : "");
  }

  void onDeactivated() override {
    Serial.println(F("[dash] SILENT"));
  }

  /* The install payload. MANIFEST first as a table of contents, so DASH can show
     a real progress bar rather than an indeterminate one, then the blocks. The
     base sends INSTALL_END after this returns. */
  void onInstall() override {
    startMsg(F("MANIFEST"));
    fieldInt(DASH_ASSET_COUNT);
    fieldInt((long)DASH_ASSET_TOTAL_BYTES);
    endMsg();

    for (uint8_t i = 0; i < DASH_ASSET_COUNT; i++) sendBlock(DASH_ASSETS[i]);
  }

 private:
  /* One asset: the header line, then exactly `length` raw bytes.

     THE BYTE COUNT IS THE FRAMING. Once the header is out, the next `length`
     bytes are payload and nothing else — a 0x0A inside a PNG is data, not a line
     ending. DASH switches to a counted read on seeing the header and switches
     back when the count is met, which is what lets binary travel down a wire that
     is otherwise line-based.

     A MODULE NEVER PARSES ITS OWN LAYOUT. This copies bytes from flash to a
     socket and understands none of them; making sense of the payload is entirely
     DASH's job. That is why an eight-bit board with an SD card could ship a panel
     it could not begin to render itself. */
  void sendBlock(const DashAsset& asset) {
    startMsg(F("BLOCK"));
    fieldRaw(asset.name);        // generated constants — no stripping needed
    fieldInt((long)asset.length);
    fieldRaw(asset.crc);
    endMsg();

    uint8_t chunk[CHUNK];
    uint32_t sent = 0;
    while (sent < asset.length) {
      uint16_t n = (asset.length - sent > CHUNK) ? CHUNK : (uint16_t)(asset.length - sent);
      for (uint16_t i = 0; i < n; i++) chunk[i] = pgm_read_byte(asset.bytes + sent + i);

      // Write the chunk out completely before moving on. A Stream may accept fewer
      // bytes than offered when its buffer is full, and a block that is even one
      // byte short is a length mismatch at the far end — after the whole payload
      // has been sent. So push the remainder rather than assuming it went.
      //
      // Deliberately NOT flush(): on the ESP32 core that drains the *receive*
      // buffer, which would quietly eat inbound DASH messages mid-install.
      uint16_t written = 0;
      while (written < n) {
        size_t w = _io->write(chunk + written, n - written);
        if (w == 0) { yield(); continue; }   // socket busy — let the stack breathe
        written += w;
      }
      sent += n;
      yield();
    }
  }

  static const uint16_t CHUNK = 512;   // one working buffer, reused for every asset

  void (*_onAction)(const char*, const char*) = nullptr;
  void (*_onActivate)() = nullptr;
};

/* -------- the module ---------------------------------------------------------- */
// A distinct id from the SYSTEM modules on the bench so all of them can coexist.
// **The version is bumped whenever the layout changes, and that is not bookkeeping.** DASH
// captured this string at install and compares it against every HELLO (roadmap 1.4.13), so a
// module whose artwork or bindings have moved on while its version stands still would keep
// being drawn from the layout already on the tablet's disk. Bumping it is what makes DASH
// quarantine the stale record and offer the update that re-runs the handshake.
DashAccessoryDraft dash("0000DA58AC01", "Tank Gauge",
                        "Air-ride tank pressure panel over WiFi", "v1.3");

/* -------- this board's own pretend tank --------------------------------------- */
// No sensor wired up (the roadmap here is about the path, not the plumbing), so the
// value is held rather than measured. It moves only when the panel asks it to.
float pressure = 0.0;
const float PRESSURE_MIN = 0.0, PRESSURE_MAX = 11.0, PRESSURE_STEP = 1.0;

unsigned long lastHeartbeat = 0;
unsigned long lastLinkTry   = 0;
const unsigned long HEARTBEAT_MS = 2000, LINK_RETRY_MS = 3000;

// Everything this module knows, said out loud. One variable today; a real one
// would say all of them here, because the panel is drawn from what DASH has been
// told and nothing else.
void dumpState() {
  dash.report("tank_pressure", pressure, 1);
}

/* A press arrived. Move the tank, clamp it, and say where it ended up.

   THE CLAMP IS NOT A REFUSAL. Pressing PLUS at 11 bar reports 11 again — the
   module heard, and could not comply, and says so by stating the truth. There is
   no error message for it and there should not be: DASH draws facts (§8), and
   the fact is that the tank did not move.

   The report goes out unconditionally, including when nothing changed, because
   this is the acknowledgement as well as the value — §8 has no separate ROGER
   for actions, and a press that produced no change still needs answering or
   DASH is left waiting on a prediction nobody will ever confirm. */
void onPanelAction(const char* control, const char* value) {
  if      (strcmp(control, "pressure_up")   == 0) pressure += PRESSURE_STEP;
  else if (strcmp(control, "pressure_down") == 0) pressure -= PRESSURE_STEP;
  else if (strcmp(control, "tank_pressure") == 0) pressure = atof(value);
  else return;                       // not ours — stay quiet rather than answer

  if (pressure > PRESSURE_MAX) pressure = PRESSURE_MAX;
  if (pressure < PRESSURE_MIN) pressure = PRESSURE_MIN;

  DBG.print(F("[dash] ")); DBG.print(control);
  DBG.print(F(" -> ")); DBG.println(pressure);
  dash.report("tank_pressure", pressure, 1);
  lastHeartbeat = millis();
}

bool linkUp = false;

/* -------- WiFi: associate, connect, and go SILENT on any drop ------------------ */
// The inversion described in BodyWifi applies here too: on USB, DASH opens the
// device; on WiFi, DASH runs the server and this module is the client that dials
// in. So the firmware's extra job is keeping that socket up — and, the important
// part, calling linkLost() the moment it is not, because a dead socket sends no
// DEACTIVATE and the module would otherwise believe it was still active.
void maintainLink() {
  if (client.connected()) { linkUp = true; return; }

  if (linkUp) {
    DBG.println(F("[wifi] link lost — going SILENT"));
    dash.linkLost();
    linkUp = false;
  }

  unsigned long now = millis();
  if (now - lastLinkTry < LINK_RETRY_MS) return;
  lastLinkTry = now;

  if (WiFi.status() != WL_CONNECTED) {
    DBG.print(F("[wifi] associating to ")); DBG.println(SECRET_SSID);
    WiFi.begin(SECRET_SSID, SECRET_PASS);
    return;                       // try the socket on a later pass
  }

  DBG.print(F("[wifi] connecting to DASH at "));
  DBG.print(DASH_HOST); DBG.print(':'); DBG.println(DASH_PORT);
  if (client.connect(DASH_HOST, DASH_PORT)) {
    DBG.println(F("[wifi] connected"));
    linkUp = true;
  }
}

void setup() {
  DBG.begin(115200);
  delay(200);
  DBG.println();
  DBG.println(F("DASH Tank Gauge (ACCESSORY over WiFi)"));
  DBG.print(F("payload: ")); DBG.print(DASH_ASSET_COUNT);
  DBG.print(F(" blocks, ")); DBG.print(DASH_ASSET_TOTAL_BYTES); DBG.println(F(" bytes"));

  WiFi.mode(WIFI_STA);
  dash.onAction(onPanelAction);  // a button on the panel was pressed
  dash.onActivate(dumpState);    // §8: the panel is correct from its first frame
  dash.begin(client);            // a WiFiClient is a Stream; the library drives it
}

void loop() {
  maintainLink();
  dash.loop();

  if (!dash.isActive()) return;  // SILENT until DASH says otherwise (§6)

  // The heartbeat (§4b). Nothing here changes a value — presses do that, the
  // moment they arrive — this only re-states what is already true, so that a
  // DASH which somehow missed a report is corrected within a couple of seconds
  // rather than for ever. DASH drops an unchanged value before it reaches the
  // store, so a resend is free and disturbs nothing.
  unsigned long now = millis();
  if (now - lastHeartbeat >= HEARTBEAT_MS) {
    lastHeartbeat = now;
    dumpState();
  }
}
