#!/usr/bin/env python3
"""Bake the Climate module's assets into a PROGMEM header (roadmap 1.6.7).

**Nothing here is this sketch's own.** This module and `ClimateWifi` are the same panel
and the same firmware down a different pipe, so this script reads ClimateWifi's assets/
AND copies its ClimateModule.h. One source, three sketches — so a difference on screen
between the three transports can only ever be the pipe, never the artwork or the logic.

Run it after changing anything in ../ClimateWifi/, then reflash. Transport: Bluetooth.

    python3 make_assets.py

Run it whenever anything in assets/ changes, then reflash. The header is generated,
never hand-edited — the files in assets/ are the source of truth, so the artwork in the
repository and the bytes on the board cannot drift apart.

**The CRC is computed here, at build time.** `module-sdk.md` §8 permits exactly that, and
it matters on a microcontroller: the alternative is reading every asset twice on every
install, once to checksum and once to send.

Format notes, both from §8:
  - CRC32, the standard zip polynomial, which is what `zlib.crc32` and `java.util.zip.CRC32`
    both implement.
  - Sent as **lowercase hex, no prefix, no padding** — exactly what Arduino's
    `String(crc, HEX)` produces, which is why `%x` is used below rather than `%08x`.
"""
import shutil
import zlib
from pathlib import Path

HERE = Path(__file__).parent
ASSETS = HERE.parent / "ClimateWifi" / "assets"

# The layout goes first so DASH meets the panel before the artwork it refers to. Nothing
# in the protocol requires that order — the install handshake is a monologue and DASH
# commits the lot at INSTALL_END — but it reads better in the Serial Monitor.
ORDER = ["h_large_day.json", "climate.svg"]

# The block name is what a layout refers to, and for a layout document it is the slot name
# (module-layout.md §9). So the layout is announced as `h_large_day`, without the .json —
# DASH knows the twelve slot names, and a block carrying one of them is a layout.
def block_name(filename: str) -> str:
    return filename[:-5] if filename.endswith(".json") else filename


def c_array(data: bytes, indent: str = "  ") -> str:
    lines = []
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(indent + row + ",")
    return "\n".join(lines)


shutil.copy(HERE.parent / "ClimateWifi" / "ClimateModule.h", HERE / "ClimateModule.h")

assets = []
for filename in ORDER:
    path = ASSETS / filename
    if not path.exists():
        raise SystemExit(f"missing asset: {path}")
    assets.append((block_name(filename), path.read_bytes()))

total = sum(len(d) for _, d in assets)

out = [
    "/* GENERATED by make_assets.py — do not edit.",
    " *",
    " * This module's install payload, baked into flash. Assets are streamed a chunk at a",
    " * time straight out of PROGMEM (module-sdk.md §8), never held whole in RAM — which is",
    " * what lets a board with kilobytes of memory ship a panel of any size.",
    " */",
    "#ifndef CLIMATE_ASSETS_H",
    "#define CLIMATE_ASSETS_H",
    "",
    "#include <Arduino.h>",
    "",
    "struct DashAsset {",
    "  const char*    name;    // the BLOCK name — a slot name means it is a layout",
    "  const uint8_t* bytes;   // in PROGMEM: read with pgm_read_byte",
    "  uint32_t       length;  // exact byte count, sent in the BLOCK header",
    "  const char*    crc;     // CRC32, lowercase hex, unpadded (§8)",
    "};",
    "",
]

for i, (name, data) in enumerate(assets):
    crc = zlib.crc32(data) & 0xFFFFFFFF
    out.append(f"// {name} — {len(data)} bytes, crc32 {crc:x}")
    out.append(f"static const uint8_t ASSET_{i}[] PROGMEM = {{")
    out.append(c_array(data))
    out.append("};")
    out.append("")

out.append("static const DashAsset DASH_ASSETS[] = {")
for i, (name, data) in enumerate(assets):
    crc = zlib.crc32(data) & 0xFFFFFFFF
    out.append(f'  {{ "{name}", ASSET_{i}, {len(data)}UL, "{crc:x}" }},')
out.append("};")
out.append("")
out.append(f"static const uint8_t  DASH_ASSET_COUNT       = {len(assets)};")
out.append(f"static const uint32_t DASH_ASSET_TOTAL_BYTES = {total}UL;")
out.append("")
out.append("#endif  // CLIMATE_ASSETS_H")

(HERE / "climate_assets.h").write_text("\n".join(out) + "\n")

for name, data in assets:
    print(f"  {name:16} {len(data):>7} bytes  crc32 {zlib.crc32(data) & 0xFFFFFFFF:x}")
print(f"  {'TOTAL':16} {total:>7} bytes in {len(assets)} blocks")
